### ISSUE TITLE
[UI] Improve Devtools header section

### ISSUE THREAD

**Issue by ryangjchandler** [amaelftah/alpinejs-devtools#29]
I'm not a big fan of the 'Alpine.js is ready' heading at the top of the dev tools. If anything, it's wasted space.

I'm suggesting we move everything up and add a cleaner title bar to the top that would maybe output the Alpine version if we can find it (maybe using the script src) along with other information like the number of components, etc.

**Comment by HugoDF** [comment]
Maybe a good opportunity to mention that we're still computing the Alpine.js state?

**Comment by ryangjchandler** [comment]
> Maybe a good opportunity to mention that we're still computing the Alpine.js state?

Yeah good shout.

**Comment by HugoDF** [comment]
Might be worth getting the version number exposed in Alpine.js

I think there's more value than just for devtools eg. Every time there's a release people are on the old version without realising.

**Comment by Te7a-Houdini** [comment]
@ryangjchandler i agree (Y) .  @HugoDF good suggestion

**Comment by HugoDF** [comment]
Relevant issue in Alpine.js is https://github.com/alpinejs/alpine/issues/398

And then we can similar to Vue:

- before we have parsed stuff -> `Detected Alpine.js vX.X.X - loading components`
- after we have parsed stuff -> `Detected Alpine.js vX.X.X - ready`
- if there is no `Alpine.version` we can fall back to `Detected Alpine.js <v2.3.1` (or whatever version is the first to have the `.version` field)

**Comment by stephenoldham** [comment]
So I hope you guys don't mind, I've had a stab at a design refresh that includes the version detection and header styling. See what you think: #55
