### ISSUE TITLE
make two separate sidebar for components and for data  

### ISSUE THREAD

**Issue by amaelftah** [amaelftah/alpinejs-devtools#3]
when there's too many components and clicking on the last component you will have to scroll up again to see this component data .so the intended behavior is something similar to vue js dev tools . is that components and data are two separate things

**Comment by HugoDF** [comment]
As part of getting stuff ready for Firefox (#4) I've been working on a responsive layout for the extension, does this fall into that kind of work?

**Comment by HugoDF** [comment]
I've been copying the Vue Devtools layout:
- Large size -> full-height, 2 columns, scrolling inside the columns
- small size -> 1 column, component is top half, data is bottom half

**Comment by HugoDF** [comment]
This is what I've got so far, will make a PR for this soon.

<img width="638" alt="Screenshot 2020-04-12 at 15 46 29" src="https://user-images.githubusercontent.com/6459679/79071656-d5cb4180-7cd4-11ea-8228-8f8c430b51f6.png">
<img width="948" alt="Screenshot 2020-04-12 at 15 46 42" src="https://user-images.githubusercontent.com/6459679/79071659-d82d9b80-7cd4-11ea-9d43-c94d64618bd1.png">

**Comment by HugoDF** [comment]
Is this fixed? The 2 panes scroll separately to one another

**Comment by Te7a-Houdini** [comment]
@HugoDF not yet i will try to work on that once i have free time
