### ISSUE TITLE
"Identifier 'connector' has already been declared" on opening devtools for 2nd time

### ISSUE THREAD

**Issue by sheraz-haider** [amaelftah/alpinejs-devtools#56]
I get this error "Uncaught SyntaxError: Identifier 'connector' has already been declared" when I close devtools and open it again on same page, and it does not detect the components on the page.

I am using this extension on Chrome 87.

Screenshot:
![image](https://user-images.githubusercontent.com/43289109/99902703-97bde380-2ce1-11eb-9b50-ee071ee00966.png)

**Comment by HugoDF** [comment]
Yeah we need to fix this

The devtools basically don't work properly with common interactions, eg. Reloading the webpage or this open/close of it see related https://github.com/amaelftah/alpinejs-devtools/issues/1

I've had a dig around but didn't manage to get it working, we might need a rethink of the architecture, the other examples I've seen (React & Vue) have an in-memory "bridge" that they use to reinitialise/cache connections
